//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoLimits2Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoLimits2Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Name&quot;:&quot;Default&quot;,&quot;components&quot;:[{&quot;constant&quot;:false,&quot;input_index&quot;:0,&quot;output_index&quot;:3,&quot;multiplierPos&quot;:1.0,&quot;multiplierNeg&quot;:1.0,&quot;offset&quot;:0.0,&quot;inverse&quot;:false,&quot;limit&quot;:-1.0,&quot;smoothing&quot;:1.0,&quot;enabled&quot;:true,&quot;math&quot;:null,&quot;spikeflatter&quot;:null,&quot;deadzone&quot;:0.0},{&quot;constant&quot;:true,&quot;input_index&quot;:7,&quot;output_index&quot;:4,&quot;multiplierPos&quot;:17.0,&quot;multiplierNeg&quot;:17.0,&quot;offset&quot;:0.0,&quot;inverse&quot;:false,&quot;limit&quot;:-1.0,&quot;smoothing&quot;:1.0,&quot;enabled&quot;:true,&quot;math&quot;:null,&quot;spikeflatter&quot;:null,&quot;deadzone&quot;:0.0},{&quot;constant&quot;:false,&quot;input_index&quot;:1,&quot;output_index&quot;:0,&quot;mul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defProfile {
            get {
                return ResourceManager.GetString("defProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;NoLimits 2 plugin for YawVR Game Engine&lt;br /&gt;
        ///Make sure to enter &amp;quot;--telemetry&amp;quot; into Launch options or into a shortcut&amp;#39;s target for non-steam version, or click PATCH GAME to place a shortcut on your desktop with this parameter.&lt;/p&gt;
        ///
        ///&lt;p&gt;Download and unzip our custom track from&amp;nbsp;&lt;a href=&quot;https://yaw.one/gameengine/Plugins/Nolimits_2/yawcoast.zip&quot;&gt;here&lt;/a&gt;. Start&amp;nbsp;No Limits2, choose Filesystem at &amp;quot;Select park&amp;quot;&amp;nbsp;window. Find YawPark from your download location, and press [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
    }
}
