//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceCombat7_dotnet8.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AceCombat7_dotnet8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///    &quot;GameName&quot;: &quot;Ace Combat 7&quot;,
        ///    &quot;Name&quot;: &quot;Default&quot;,
        ///    &quot;Components&quot;: [
        ///        {
        ///            &quot;Constant&quot;: false,
        ///            &quot;Input_index&quot;: 6,
        ///            &quot;Output_index&quot;: 0,
        ///            &quot;MultiplierPos&quot;: 1.0,
        ///            &quot;MultiplierNeg&quot;: 1.0,
        ///            &quot;Offset&quot;: 0.0,
        ///            &quot;Inverse&quot;: false,
        ///            &quot;Limit&quot;: -1.0,
        ///            &quot;Smoothing&quot;: 1.0,
        ///            &quot;Enabled&quot;: true,
        ///            &quot;Spikeflatter&quot;: {
        ///                &quot;Enabled&quot;: false,
        ///                &quot;Limit&quot;: 100.0,
        ///         [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string defaultProfile {
            get {
                return ResourceManager.GetString("defaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h1&gt;UEVR Installation Guide&lt;/h1&gt;
        ///&lt;h2&gt;Installation Steps&lt;/h2&gt;
        ///&lt;ol&gt;
        ///    &lt;li&gt;Download &lt;a href=&quot;https://github.com/praydog/UEVR-nightly/releases&quot; target=&quot;_blank&quot;&gt;the latest UEVR Nightly version&lt;/a&gt; and extract it to any location.&lt;/li&gt;
        ///    &lt;li&gt;Download UESS from &lt;a href=&quot;https://www.nexusmods.com/acecombat7skiesunknown/mods/2474?tab=files&quot; target=&quot;_blank&quot;&gt;this link&lt;/a&gt; and extract the files into the game folder located at &quot;...\common\ACE COMBAT 7&quot;.&lt;/li&gt;
        ///    &lt;li&gt;Create the following directories:
        ///        &lt;ul [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
    }
}
